const mongoose = require("mongoose");

const db = require("./models");

let timStory = [`You slowly open your eyes and see the somewhat depressing and dark ceiling illuminated by artificial light.`,
`...another day of being stuck in this killing game.`,
`You think about all of the previous murders and tasteless executions as you sit up on your bed.`,
`There’s only 7 of you left now.`,
"<OPTION><CHOSEN>Where would you like to go for the Morning Meeting?|Stay in Your Room|>Cafeteria<",
"<SCENE TRANSITION>Cafeteria.png",
"You make your way to the dining hall where you meet with the other remaining 6 students:",
"Ultimate High School Mathematician: <br>Kawasaki Dayu",
"Ultimate High School Luckster: <br>Skylar Snappington",
"Ultimate High School Evil Overlord: <br>Adam Sandler",
"Ultimate High School Football Player: <br>Antonio Candelario",
"Ultimate High School Footbal Player: <br>Nicholas Johnson",
"Ultimate High School Fisherman: <br>Drew Gahagan",
"When you get there you are surprised to find the Ultimate Luckster, Skylar Snappington already sitting at the table.",
"You are usually the first one to the morning meeting as everyone else tends to sleep in somewhat and you show up rather early.",
`"You’re up rather early today. Might I inquire as to why?” you ask politely.`,
'“...couldn’t sleep.” he responds with a bit of a defeated expression.',
`The poor boy seems to be rather shaken by the string of murders and executions lately.`,
`“...we need to make sure to not let anyone else die.” he says with empty conviction.`,
`Before you can say anything in response the door opens to reveal the self proclaimed Ultimate Evil Overlord, Adam Sandler, though you are heavily inclined to believe that this is a lie, for reasons that should be evident to anyone who interacts with him.`,
`The Evil Overlord takes a seat on the other side of the table, next to Skylar, and then puts his feet up on it in an incredibly arrogant and pompous manner.`,
`It is at that exact moment that the door bursts open and in comes barrelling the Ultimate HIgh School Football Player, Nicholas Johnson.`,
`“Raaaaaaargh!”`,
`He runs into the room with an incredibly loud, and if you are to be honest quite irritating, yell at the top of his lungs and then throws a football onto his seat while yelling “TOUCHDOOWWWN!”`,
`“Good Morning, Mr. Sandler. Nicholas.” you say to each of them in turn.`,
`“As expected of the Adam Sandler’s most valuable minion!” says Sandler in a dramatic voice. “Quite the impressive entrance!”`,
`“Hah!” the football player picks up the football and throws it back down on the ground again for some reason before plopping down into the seat next to the Evil Overlord.`,
`“So minion-in-training.” Sandler says towards you`,
`“...my names Skylar.” you remind him for the ump-teenth time.`,
`“Yes, Skylar, my minion-in-training. I can’t help but notice you’re looking rather gloomy today. What’s up with that?”`,
`"...just can't help but think about all of the terrible things that have happened so far. ...but I won't let it defeat me. We can't let the mastermind beat any of us!" Skylar says with his best attempt at confidence.`,
`"Of course, of course. Can't have this unknown mastermind usurping THE Adam Sandler in evilness I agree completely. It's high time we unmasked the culprit and restored my rightful place as Supreme Overlord."`,
`At this time, the other Ultimate Football Player, Antonio Candelario comes walking into the room looking rather displeased. Upon seeing this Nick calls out triumphantly:`,
`"HAH! Yet again I have bested you in FOOT BALL, you FAKE!" Nick throws another football.`,
`"I keep telling you that the barbaric sport you partake in is fortunately nothing like the sport I play, and that I have no interest in your stupid games." Antonio says while taking a seat with a displeased expression`,
`"Hah! Antonio is a sore loser. He's just upset that I am. THE BEST. FOOTBALL PLAYER! No-one can challenge me!"`,
`Nick proceeds to yell like an ape as he bangs his chest.`,
`Antonio simply looks back at him with a glare and says nothing.`,
`"Good work minion! Continue to boast of your victory over those weaker than you! THE Adam Sandler is pleased with your victory!"`,
`"I keep saying- It wasnt- He's not- Argh!" Antonio trys to respond flustered.`,
`At that time the door opens to reveal the Ultimate Fisherman looking a little sleepy. "G'mornin..." He says before slumping into a seat.`,
`The six of you sit and talk for a while. You manage to learn that the Luckster is feeling rather dejected about the recent string of deaths and is trying his best to not succumb to the despair inflicted by them. Other than that nothing noteworthy really is discussed until finally the door opens and the Ultimate Mathematician finally comes in.`,
`"Alright guys. So I've been running the numbers, and this is what I think the probability for the next murder is."`,
`He throws down a bunch of papers on the table. Upon further examination they propose the following:`,
`Ultimate (American) Football Player Probabilities: <br>50% chance of commiting murder <br>37.21% Chance of being killed by The Ultimate (International) Football Player <br>1.68% Chance of being killed by The Ultimate Fisherman <br>3.34% Chance of being killed by The Ultimate Mathematician <br>0% Chance of being killed by The Ultimate Luckster <br>Incalculable Chance of being killed by The Ultimate Actor <br>5.65% Chance of being killed by The Ultimate Secretary`,
`Ultimate (International) Football Player Probabilities:<br>24% Chance of Committing Murder<br>45.33% Chance of being killed by The Ultimate (American) Football Player<br>.9% Chance of being killed by The Ultimate Fisherman<br>1.79% Chance of being killed by The Ultimate Mathematician<br>0% Chance of being killed by The<br>Ultimate Luckster<br>Inalculable Chance of being killed by The Ultimate Actor<br>4.19% Chance of being killed by The Ultimate Secretary`,
`Ultimate Fisherman AND Mathematician Probabilities: (Probability is the same)<br>0.1% Chance of Comitting Murder<br>4.93 - Killed by American Football<br>2.18% - Killed by International Football<br>.02% - killed by Math/Fisher<br>0% - killed by Luckster<br>Incalculable Actor<br>2.51% killed by Secretary`,
`Luckster Probabilities:<br>0% Chance of Comitting Murder<br>8.33% - Killed by American Football<br>4% - Killed by International Football<br>.1% Killed by Fisherman<br>.1% Killed by Math<br>Incalculable Actor<br>3.83% Secretary`,
`Actor: Incalculable`,
`Secretary:<br>23% Chance of Committing Murder<br>6.41% - Killed by American Football<br>2.83% - Killed by International Football<br>1.3% - Killed by Fisher<br>0% - Killed by Luckster<br>Incalculable Actor<br>1.3% - Killed by Math`,
`"Would you like me to copy these for everyone, Mr. Kawasaki?" you ask pulling out a pen.`,
`The mathematician shakes his head. "That's unnecessary. I can just print some more if anybody wants copies." he says. "Come see me later if you do."`,
`"Why are my probabilities so... incalculable?" Adam asks.`,
`"...I can't predict what you would do even if I tried. ...which I have." is his response.`,
`"How exactly are your probabilities determined?" you ask.`,
`"Hmm..." he says. "While I wouldn't mind explaining the details at a later time, doing so in current company feels rather..." he looks around. "...pointless. Just know that they are accurate." he says with an uncharcteristic amount of confidence.`,
`"...why do you think it's so likely that Nick will... murder someone?" the Luckster asks.`,
`"It's because all of you are too puny. I could kill you just by breathing too hard." Nick responds.`,
`"...look there are a lot of variables involved, don't worry about it. Like I said if you really wanna know the details we can talk about it later." the Mathematician says.`,
`The group falls into a brief silence as you all study the probabilities a bit more...`,
`<OPTION><CHOSEN>Choose a Topic of Inquiry!|>Discuss the Probabilities at Length<|Explore the School|Discuss Escape Plans|None`,
`"Alright alright that's enough math for today. Minions! Let us commence the traditional exploration period!" Adam claps his hands together. "We shall meet in the cafeteria at noon to discuss our findings! Adam Sandler has spoken! Most Valued Minion, you're with me, let us be off."`,
`He and Nick leave before anyone can respond.`,
`"...uh. Well I was gonna suggest we do that anyway. Guess we'll meet up in a couple hours." the Luckster says, to which everyone else nods.`,
`...Oh well you can always discuss the probabilities later you suppose.`,
`<MUSIC>beautifulLie`,
`<OPTION><CHOSEN>Choose a New Location to Explore|Game Room|>Ultimate Evil Lair<|Ultimate Lucky Lab`,
`<SCENE TRANSITION>hallway.png`,
`You head to the new Evil Lair. As you get there, you see Nick, the ultimate Football player standing outside. Suddenly Adam Sandler comes bursting through the door wearing football gear.`,
`<MUSIC>peaceParty`,
`"...you've finally decided to show your true powers. Very well I accept your challenge." Nick says as he pulls out a football.`,
`"Time to open up some whoop-ass!" Adam says in a strange voice.`,
`"2-player football. Rules are simple. I throw football up in air, we fight to be the one to score a touchdown at the cafeteria. You ready?" Nick asks Adam.`,
`Neither of them seem to have realised your presence.`,
`"Might I suggest I be the referee for this game?" you ask them.`,
`Adam gets in a baseball stance and says "I'm ready."`,
`You accept that that's probably the closest to a yes you'll get from either of them, and so quickly head to the cafeteria to do your job, rushing ahead of the two of them to make sure they don't suddenly pass you up during the game.`,
`Seemingly the instant you reach the cafeteria you hear a weird screaching noise as Adam comes barreling into the Cafeteria behind you.`,
`He rushes straight past you and out the door on the other side. Nick then runs into the cafeteria with a look of defeat.`,
`Adam then re-enters sans football/football gear and asks: "Soo.... what happened?"`,
`"I declare the winner of this game of 2-Player Football: Adam Sandler! ...with second place going to Nick of course." you say.`,
`<MUSIC>moonWater`,
`Nick falls on the ground staring at the floor in disbelief.`,
`"Don't beat yourself up too much Nick. If Evil Overlords could be so easily overthrown, they wouldn't be Evil Overlords." you say.`,
`"....I was beaten. How... can the ultimate be beaten? I'm not the Ultimate Football Player. I'm the Ultimate Nothing." Nick says on his knees staring at the ground.`,
`"It's ok Nick. What you just played wasn't really football." you say trying to reassure him.`,
`"Wasn't football?! It was definitely football! It's in the name! Two-player football!" he responds.`,
`"Mwahahaha!" Adam exclaims "My friend, this is why you do NOT question the ultimate Adam Sandler. Because some how, some way, he never goes away."`,
`You ignore Adam's bizarre proclomation and continue trying to assauge Nick.`,
`"Nick. If we called an airplane a "Football Airplane" that wouldn't mean you are any better a pilot, and as such, calling what is basically a race with a ball "2-man Football" doesn't indicate your skill in true football. ...also, being the minion of the Ultimate Evil Overlord might be affecting Adam's performance against you."`,
`Nick shakes his head. "It was football. I would know. ...or maybe I don't. Maybe I don't know anything." he looks down at his hands. "But wait but then if it wasn't football... that means I'm still the Ultimate! But if I'm the Ultimate and I call something football and then lose at it... then how can I be Ultimate?" Nick looks like he's about to have a mental breakdown from the percieved paradox.`,
`"Don't worry Nick, we'll get to the bottom of it." You say with a reassuring voice as you help him up.`,
`"Yeah..." he says still looking dejected. "I think I'm gonna go to my room. ...rethink some things." He leaves the room.`
 ];
for(let x=0; x<timStory.length; x++){
    timStory[x] = {story: timStory[x], id: "None"};
};
console.log(timStory);
db.Story.create({chapter:1, day:1, time:"morning", player: "Tim",
story: timStory});

let cameronStory = ["You wake up. Another morning after another trial...",
"...another day as THE Adam Sandler: the evil overlord who used his charisma and acting fame to build an army and take over the world!",
"You leap up from bed and prepare for another day of evil...",
"<OPTION><CHOSEN>Where would you like to go for the Morning Meeting?|Stay in Your Room|>Cafeteria<",
"<SCENE TRANSITION>Cafeteria.png",
"You make your way to the dining hall where you meet with the other remaining 6 students:",
"Ultimate High School Mathematician: <br>Kawasaki Dayu",
"Ultimate High School Luckster: <br>Skylar Snappington",
"Ultimate High School Secretary: <br>Ishikawa Shiori",
"Ultimate High School Football Player: <br>Antonio Candelario",
"Ultimate High School Footbal Player: <br>Nicholas Johnson",
"Ultimate High School Fisherman: <br>Drew Gahagan",
"You enter the dining room to see the Secretary and the Luckster sitting at the table. You stroll in while making sure to assert your dominance as the Ultimate Evil Overlord THE Adam Sandler.",
"You take a seat next to the Luckster and prop your feet up on the table in a suitably evil fashion.",
"It is at this exact moment that the door bursts open and in comes barrelling the Ultimate High School Football Player, Nicholas Johnson.",
'He runs into the room with an incredibly loud yell at the top of his lungs and then throws a football onto his seat while yelling “TOUCHDOOWWWN!”',
'“Good Morning, Mr. Sandler. Nicholas.” the Secretary says in a business like manner to the two of you.',
`“As expected of THE Adam Sandler's most valued minion.” you say dramatically in reaction to Nick’s flamboyant entrance. “Quite the impressive entrance!”`,
`“Hah!” the football player picks up the football and throws it back down on the ground again before plopping down into the seat next to you.`,
`“So minion-in-training.” you say towards Skylar.`,
`“...my names Skylar.”`,
`“Yes, Skylar, my minion-in-training. I can’t help but notice you’re looking rather gloomy today. What’s up with that?”`,
`"...just can't help but think about all of the terrible things that have happened so far. ...but I won't let it defeat me. We can't let the mastermind beat any of us!" Skylar says with what little vigor he can muster.`,
`"Of course, of course. Can't have this unknown mastermind usurping THE Adam Sandler in evilness I agree completely. It's high time we unmasked the culprit and restored my rightful place as Supreme Overlord."`,
`At this time, the other Ultimate Football Player, Antonio Candelario comes walking into the room looking rather displeased. Upon seeing this Nick calls out triumphantly:`,
`"HAH! Yet again I have bested you in FOOT BALL, you FAKE!" Nick throws another football.`,
`"I keep telling you that the barbaric sport you partake in is fortunately nothing like the sport I play, and that I have no interest in your stupid games." Antonio says while taking a seat with a displeased expression`,
`"Hah! Antonio is a sore loser. He's just upset that I am. THE BEST. FOOTBALL PLAYER! No-one can challenge me!"`,
`Nick proceeds to yell like an ape as he bangs his chest.`,
`Antonio simply looks back at him with a glare and says nothing.`,
`"Good work minion! Continue to boast of your victory over those weaker than you! THE Adam Sandler is pleased with your victory!"`,
`"I keep saying- It wasnt- He's not- Argh!" Antonio trys to respond flustered.`,
`At that time the door opens to reveal the Ultimate Fisherman looking a little sleepy. "G'mornin..." He says before slumping into a seat.`,
`The six of you sit and talk for a while. You manage to learn that the Luckster is feeling rather dejected about the recent string of deaths and is trying his best to not succumb to the despair inflicted by them. Other than that nothing noteworthy really is discussed until finally the door opens and the Ultimate Mathematician finally comes in.`,
`"Alright guys. So I've been running the numbers, and this is what I think the probability for the next murder is."`,
`He throws down a bunch of papers on the table. Upon further examination they propose the following:`,
`Ultimate (American) Football Player Probabilities: <br>50% chance of commiting murder <br>37.21% Chance of being killed by The Ultimate (International) Football Player <br>1.68% Chance of being killed by The Ultimate Fisherman <br>3.34% Chance of being killed by The Ultimate Mathematician <br>0% Chance of being killed by The Ultimate Luckster <br>Incalculable Chance of being killed by The Ultimate Actor <br>5.65% Chance of being killed by The Ultimate Secretary`,
`Ultimate (International) Football Player Probabilities:<br>24% Chance of Committing Murder<br>45.33% Chance of being killed by The Ultimate (American) Football Player<br>.9% Chance of being killed by The Ultimate Fisherman<br>1.79% Chance of being killed by The Ultimate Mathematician<br>0% Chance of being killed by The<br>Ultimate Luckster<br>Inalculable Chance of being killed by The Ultimate Actor<br>4.19% Chance of being killed by The Ultimate Secretary`,
`Ultimate Fisherman AND Mathematician Probabilities: (Probability is the same)<br>0.1% Chance of Comitting Murder<br>4.93 - Killed by American Football<br>2.18% - Killed by International Football<br>.02% - killed by Math/Fisher<br>0% - killed by Luckster<br>Incalculable Actor<br>2.51% killed by Secretary`,
`Luckster Probabilities:<br>0% Chance of Comitting Murder<br>8.33% - Killed by American Football<br>4% - Killed by International Football<br>.1% Killed by Fisherman<br>.1% Killed by Math<br>Incalculable Actor<br>3.83% Secretary`,
 `Actor: Incalculable`,
 `Secretary:<br>23% Chance of Committing Murder<br>6.41% - Killed by American Football<br>2.83% - Killed by International Football<br>1.3% - Killed by Fisher<br>0% - Killed by Luckster<br>Incalculable Actor<br>1.3% - Killed by Math`,
 `"Would you like me to copy these for everyone, Mr. Kawasaki?" the Secretary asks pulling out a pen.`,
 `The mathematician shakes his head. "That's unnecessary. I can just print some more if anybody wants copies." he says. "Come see me later if you do."`,
 `"Why are my probabilities so... incalculable?" you ask.`,
 `"...I can't predict what you would do even if I tried. ...which I have." is his response.`,
 `"How exactly are your probabilities determined?" the Secretary asks.`,
 `"Hmm..." he says. "While I wouldn't mind explaining the details at a later time, doing so in current company feels rather..." he looks around. "...pointless. Just know that they are accurate." he says with an uncharcteristic amount of confidence.`,
 `"...why do you think it's so likely that Nick will... murder someone?" the Luckster asks.`,
 `"It's because all of you are too puny. I could kill you just by breathing too hard." Nick responds.`,
 `"...look there are a lot of variables involved, don't worry about it. Like I said if you really wanna know the details we can talk about it later." the Mathematician says.`,
 `The group falls into a brief silence as you all study the probabilities a bit more...`,
 `<OPTION><CHOSEN>Choose a Topic of Inquiry!|Discuss the Probabilities at Length|>Explore the School<|Discuss Escape Plans|None`,
 `"Alright alright that's enough math for today. Minons! Let us commence the traditional exploration period!" You clap your hands together. "We shall meet in the cafeteria at noon to discuss our findings! Adam Sandler has spoken! Most Valued Minion, you're with me, let us be off."`,
 `You leave the room with Nick before anyone can respond and head off to the newly opened section of the school.`,
 `<MUSIC>beautifulLie`,
 `<OPTION><CHOSEN>Choose a New Location to Explore|Game Room|>Ultimate Evil Lair<|Ultimate Lucky Lab`,
 `<SCENE TRANSITION>hallway.png`,
 `You immediately head to your new lair and use your key to unlock the massive doors leading into it.`,
 `<OPTION><CHOSEN>Let Nick follow you inside?|Yes|>No<`,
 `"Wait here friend, let me see if there is anything interesting or dangerous. It would be a shame to lose a trusted ally over nothing huh?" you say to Nick.`,
 `He shrugs in response.`,
 `<SCENE TRANSITION>theater.jpg`,
 `You enter the room and find... an auditoritum. Curtains drawn.`,
 `You walk backstage and there are countless costumes and props that could help you take on different roles. On the stage itself you see what could be fairly aptly described as an "Evil Lair". You pull open the curtains and the lights shine in on your Evil Lair.`,
 `Suddenly you are struck with inspiration. You look through your Adam Sandler gear and find your Bobby Boucher football gear. You quickly put it on becoming BOBBY BOUCHER! ...and then rush out of the auditorium.`,
 `<SCENE TRANSITION>hallway.png`,
 `Upon seeing you, Nick's eyes immediately sharpen.`,
 `<MUSIC>peaceParty`,
 `"...you've finally decided to show your true powers. Very well I accept your challenge." He pulls out a football.`,
 `"Time to open up some whoop-ass!" you say.`,
 `"2-player football. Rules are simple. I throw football up in air, we fight to be the one to score a touchdown at the cafeteria. You ready?" Nick asks you.`,
 `"Might I suggest I be the referee for this game?" Shiori, the Secretary suddenly shows herself.`,
 `You get in a baseball stance and say "I'm ready." Shiori apparently takes this as a yes to her question, and quickly rushes to the cafeteria to do her job.`,
 `After a brief period Nick throws the ball up in the air initating combat.`,
 `You go for the football, but Nick reaches it first. Not to be deterred, you let out your Bobby Boucher shriek and run into Nick head on.`,
 `With him not expecting your sheer power, you manage to knock him down and then take the football from him. He chases after you, but nobody can stop Bobby Boucher!`,
 `<SCENE TRANSITION>Cafeteria.png`,
 `You rush into the cafeteria at full speed. You keep running. You don't stop. You run right past Shiori and through the Cafeteria and burst out the door on the other side.`,
  `<SCENE TRANSITION>hallway.png`,
  `After passing through the door you regain a bit of yourself, and promptly take off the football gear before heading back inside the cafeteria.`,
  `<SCENE TRANSITION>Cafeteria.png`,
  `<MUSIC>moonWater`,
  `"So ... what happened?" you ask.`,
  `"I declare the winner of this game of 2-Player Football: Adam Sandler! ...with second place going to Nick of course." Shiori announces.`,
  `Nick falls on the ground staring at the floor in disbelief.`,
  `"Don't beat yourself up too much Nick. If Evil Overlords could be so easily overthrown, they wouldn't be Evil Overlords." Shiori says.`,
  `"....I was beaten. How... can the ultimate be beaten? I'm not the Ultimate Football Player. I'm the Ultimate Nothing." Nick says on his knees staring at the ground.`,
  `"It's ok Nick. What you just played wasn't really football." Shiori says trying to reassure him.`,
  `"Wasn't football?! It was definitely football! It's in the name! Two-player football!" he responds.`,
  `"Mwahahaha!" you exclaim "My friend, this is why you do NOT question the ultimate Adam Sandler. Because some how, some way, he never goes away!" you exclaim.`,
  `"Nick. If we called an airplane a "Football Airplane" that wouldn't mean you are any better a pilot, and as such, calling what is basically a race with a ball "2-man Football" doesn't indicate your skill in true football. ...also, being the minion of the Ultimate Evil Overlord might be affecting Adam's performance against you." Shiori says to Nick.`,
  `Nick shakes his head. "It was football. I would know. ...or maybe I don't. Maybe I don't know anything." he looks down at his hands. "But wait but then if it wasn't football... that means I'm still the Ultimate! But if I'm the Ultimate and I call something football and then lose at it... then how can I be Ultimate..." Nick looks like he's about to have a mental breakdown from all this thinking.`,
  `"Don't worry Nick. We'll get to the bottom of it." you say.`,
  `He looks a little out of it as he responds "...yeah. I'm gonna... Go to my room. Think about some things."`];
  for(let x=0; x<cameronStory.length; x++){
    cameronStory[x] = {story: cameronStory[x], id: "None"};
};
db.Story.create({chapter: 1, day: 1, time: "morning", player: "Cameron",story: cameronStory})

let kristianStory = [`<MUSIC>moonWater`,
"You groggily get up, feeling terrible. Your brain spent the night replaying all of the deaths and executions you’ve seen up till now, making sure that the despair and terror was fresh in your mind.", 
"...there’s only 7 of you left now.",
`But none of you were about to let the mastermind have his/her way any longer!`,
`…right?`,
`You slowly push yourself out of bed as you think about these things and head to the dining hall for the morning meeting.`,
"<OPTION><CHOSEN>Where would you like to go for the Morning Meeting?|Stay in Your Room|>Cafeteria<",
"<SCENE TRANSITION>Cafeteria.png",
`<MUSIC>morning`,
"You get to the dining hall first. ...you weren’t able to sleep very well due to stress and so you’re up kind of early. ",
"You idle the time away by thinking about everything that’s happened, and what you might say to try and cheer everybody up after all of the tragedy.",
"Not long after you enter, Ishikawa-san comes in. She looks stern and business-like as usual as she sits across from you at the table.",
"She looks at you with a small look of questioning.",
'“You’re up rather early today. Might I inquire as to why?” she asks politely.',
'“...couldn’t sleep.” you respond.',
`You are again reminded of the visions of death keeping you awake.`,
`“...we need to make sure to not let anyone else die.” you say with what is hopefully conviction as you clench your fist.`,
`Before Ishikawa-san can respond, in comes the self-proclaimed evil overlord Adam Sandler. ….you don’t really like this guy. Bit of an annoying agent of chaos that stirs up trouble. ...but a point of pride of yours is your ability to make friends with anyone so you’ll do your best to overlook it.`,
`Anyway Adam Sandler enters the room in his strangely pompous style and then sits next to you with his feet propped up on the table.
It’s at this time that the door to the Dining Hall BURSTS open and Nick comes barreling in with a yell.`,
`“Raaaaaaargh!”`,
`You would be alarmed if this wasn’t how he always entered the room.`,
`As usual, he runs up to the table, and then throws a football onto his chair while yelling “TOOOUCHDOWN!”`,
`“Good morning, Mr. Sandler, Nicholas.” the Secretary says in her usual polite manner to the two newcomers.`,
`“As expected of the Adam Sandler’s most valuable minion!” says Sandler in a dramatic voice. “Quite the impressive entrance!”`,
`“Hah!” the football player picks up the football and throws it back down on the ground again for some reason before plopping down into the seat next to the Evil Overlord.`,
`...at least half of the people remaining are completely insane. You’re not really sure how you should feel about this, but it’s definitely worrying.`,
`“So minion-in-training.” Sandler says towards you`,
`“...my names Skylar.” you remind him for the ump-teenth time.`,
`“Yes, Skylar, my minion-in-training. I can’t help but notice you’re looking rather gloomy today. What’s up with that?”`,
`"...just can't help but think about all of the terrible things that have happened so far. ...but I won't let it defeat me. We can't let the mastermind beat any of us!" you say with vigor to a mostly unappreciative and uninterested audience.`,
`"Of course, of course. Can't have this unknown mastermind usurping THE Adam Sandler in evilness I agree completely. It's high time we unmasked the culprit and restored my rightful place as Supreme Overlord."`,
`At this time, the other Ultimate Football Player, Antonio Candelario comes walking into the room looking rather displeased. Upon seeing this Nick calls out triumphantly:`,
`"HAH! Yet again I have bested you in FOOT BALL, you FAKE!" Nick throws another football.`,
`"I keep telling you that the barbaric sport you partake in is fortunately nothing like the sport I play, and that I have no interest in your stupid games." Antonio says while taking a seat with a displeased expression`,
`"Hah! Antonio is a sore loser. He's just upset that I am. THE BEST. FOOTBALL PLAYER! No-one can challenge me!"`,
`Nick proceeds to yell like an ape as he bangs his chest.`,
`Antonio simply looks back at him with a glare and says nothing.`,
`"Good work minion! Continue to boast of your victory over those weaker than you! THE Adam Sandler is pleased with your victory!"`,
`"I keep saying- It wasnt- He's not- Argh!" Antonio trys to respond flustered.`,
`At that time the door opens to reveal the Ultimate Fisherman looking a little sleepy. "G'mornin..." He says before slumping into a seat.`,
`The six of you sit and talk for a while. You try and cheer yourself up by giving a speech about friendship but it rings a bit hollow and nobody seems too impressed. Other than that nothing noteworthy really is discussed until finally the door opens and the Ultimate Mathematician finally comes in.`,
`"Alright guys. So I've been running the numbers, and this is what I think the probability for the next murder is."`,
`He throws down a bunch of papers on the table. Upon further examination they propose the following:`,
`Ultimate (American) Football Player Probabilities: <br>50% chance of commiting murder <br>37.21% Chance of being killed by The Ultimate (International) Football Player <br>1.68% Chance of being killed by The Ultimate Fisherman <br>3.34% Chance of being killed by The Ultimate Mathematician <br>0% Chance of being killed by The Ultimate Luckster <br>Incalculable Chance of being killed by The Ultimate Actor <br>5.65% Chance of being killed by The Ultimate Secretary`,
`Ultimate (International) Football Player Probabilities:<br>24% Chance of Committing Murder<br>45.33% Chance of being killed by The Ultimate (American) Football Player<br>.9% Chance of being killed by The Ultimate Fisherman<br>1.79% Chance of being killed by The Ultimate Mathematician<br>0% Chance of being killed by The<br>Ultimate Luckster<br>Inalculable Chance of being killed by The Ultimate Actor<br>4.19% Chance of being killed by The Ultimate Secretary`,
`Ultimate Fisherman AND Mathematician Probabilities: (Probability is the same)<br>0.1% Chance of Comitting Murder<br>4.93 - Killed by American Football<br>2.18% - Killed by International Football<br>.02% - killed by Math/Fisher<br>0% - killed by Luckster<br>Incalculable Actor<br>2.51% killed by Secretary`,
`Luckster Probabilities:<br>0% Chance of Comitting Murder<br>8.33% - Killed by American Football<br>4% - Killed by International Football<br>.1% Killed by Fisherman<br>.1% Killed by Math<br>Incalculable Actor<br>3.83% Secretary`,
 `Actor: Incalculable`,
 `Secretary:<br>23% Chance of Committing Murder<br>6.41% - Killed by American Football<br>2.83% - Killed by International Football<br>1.3% - Killed by Fisher<br>0% - Killed by Luckster<br>Incalculable Actor<br>1.3% - Killed by Math`,
 `"Would you like me to copy these for everyone, Mr. Kawasaki?" the Secretary asks pulling out a pen.`,
 `The mathematician shakes his head. "That's unnecessary. I can just print some more if anybody wants copies." he says. "Come see me later if you do."`,
 `"Why are my probabilities so... incalculable?" Adam asks.`,
 `"...I can't predict what you would do even if I tried. ...which I have." is his response.`,
 `"How exactly are your probabilities determined?" the Secretary asks.`,
 `"Hmm..." he says. "While I wouldn't mind explaining the details at a later time, doing so in current company feels rather..." he looks around. "...pointless. Just know that they are accurate." he says with an uncharcteristic amount of confidence.`,
 `"...why do you think it's so likely that Nick will... murder someone?" you ask.`,
 `"It's because all of you are too puny. I could kill you just by breathing too hard." Nick responds.`,
 `"...look there are a lot of variables involved, don't worry about it. Like I said if you really wanna know the details we can talk about it later." the Mathematician says.`,
 `The group falls into a brief silence as you all study the probabilities a bit more...`,
 `<OPTION><CHOSEN>Choose a Topic of Inquiry!|Discuss the Probabilities at Length|>Explore the School<|Discuss Escape Plans|None`,
 `"Alright alright that's enough math for today. Minions! Let us commence the traditional exploration period!" You clap your hands together. "We shall meet in the cafeteria at noon to discuss our findings! Adam Sandler has spoken! Most Valued Minion, you're with me, let us be off."`,
 `He and Nick leave before anyone can respond.`,
 `"...uh. Well I was gonna suggest we do that anyway. Guess we'll meet up in a couple hours."`,
 `The rest nod and you begin your investigation.`,
 `<MUSIC>beautifulLie`,
 `<OPTION><CHOSEN>Choose a New Location to Explore|Game Room|Ultimate Evil Lair|>Ultimate Lucky Lab<`,
 `<SCENE TRANSITION>hallway.png`,
 `You head to the Ultimate Lucky Lab... alone apparently. Well at least you can investigate your own lab in peace. You honestly have no idea what to expect. It's not like luck is a special skill you've been cultivating your whole life or something...`,
 `<SCENE TRANSITION>Lounge.png`,
 `You use your key to unlock your lab and inside see... an incredibly normal lounge room. After a bit of searching the room has a lot of different dice and cards and other luck based games but other than that there's nothing too interesting..`
];
for(let x=0; x<kristianStory.length; x++){
    kristianStory[x] = {story: kristianStory[x], id: "None"};
};
db.Story.create({chapter: 1, day: 1, time: "morning", player: "Kristian", 
story: kristianStory}); 